#!/usr/bin/env bash
# Generate one Meson cross-file per target PLATFORM, pointing at the Xcode clang
# toolchain (resolved via xcrun) and injecting the -arch/-isysroot/min-version
# flags every iOS compile and link step needs.
#
# Usage:
#   gen-cross-files.sh [platform ...]
#
# With no arguments both platforms are generated; otherwise only the named ones.
# The per-platform install prefix (<base>/<platform>) is taken from
# $NORDSTJERNEN_IOS_SYSROOT and baked into each cross-file's pkg_config_libdir so
# Meson resolves the already-built dependencies.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

require_toolchain

SYSROOT_BASE="${NORDSTJERNEN_IOS_SYSROOT:-${IOS_DIR}/sysroot}"
mkdir -p "${CROSS_DIR}"

gen_one() {
  local platform="$1"
  set_platform_env "${platform}"
  local prefix="${SYSROOT_BASE}/${platform}"
  local out="${CROSS_DIR}/${platform}.cross"

  cat > "${out}" <<EOF
# Auto-generated by ios/scripts/gen-cross-files.sh -- DO NOT EDIT BY HAND.
# Target platform: ${platform}   SDK: ${PLATFORM_SDK}   iOS min: ${IOS_DEPLOYMENT_TARGET}
[constants]
common_args = ['-arch', '${PLATFORM_ARCH}', '-isysroot', '${SDKROOT}', '${PLATFORM_MIN_FLAG}']

[binaries]
c          = '${CC}'
cpp        = '${CXX}'
objc       = '${CC}'
ar         = '${AR}'
strip      = '${STRIP}'
ranlib     = '${RANLIB}'
nm         = '${NM}'
pkg-config = 'pkg-config'

[built-in options]
# Two Darwin/iOS fixes for every C compile:
#  - _DARWIN_C_SOURCE exposes Darwin's non-POSIX extensions.
#  - force-include <xlocale.h>, which declares locale_t and the LC_*_MASK
#    constants that some deps (fontconfig's fcint.h) use unconditionally but do
#    not themselves include under the iOS cross-configure. _DARWIN_C_SOURCE
#    alone is not enough — the header must actually be pulled in.
c_args          = common_args + ['-fPIC', '-O2', '-D_DARWIN_C_SOURCE', '-include', 'xlocale.h']
cpp_args        = common_args + ['-fPIC', '-O2', '-D_DARWIN_C_SOURCE']
objc_args       = common_args + ['-fPIC', '-O2', '-D_DARWIN_C_SOURCE']
c_link_args     = common_args
cpp_link_args   = common_args
objc_link_args  = common_args
default_library = 'static'

[properties]
# Built dependencies install with an absolute prefix, so their .pc files carry
# absolute paths; we therefore set pkg_config_libdir but NOT sys_root.
pkg_config_libdir = '${prefix}/lib/pkgconfig'
needs_exe_wrapper = true

[host_machine]
system     = 'darwin'
subsystem  = '${PLATFORM_SUBSYSTEM}'
cpu_family = '${PLATFORM_CPU_FAMILY}'
cpu        = '${PLATFORM_CPU}'
endian     = '${PLATFORM_ENDIAN}'
EOF
  log "wrote ${out}"
}

if [ "$#" -ge 1 ]; then
  PLATFORMS=("$@")
else
  PLATFORMS=("${ALL_PLATFORMS[@]}")
fi

for platform in "${PLATFORMS[@]}"; do
  is_valid_platform "${platform}" || die "unknown platform: ${platform}"
  gen_one "${platform}"
done
