#!/usr/bin/env bash
# Generate one Meson cross-file per target ABI, pointing at the NDK r27 clang
# toolchain and injecting the 16 KB max-page-size link flag.
#
# Usage:
#   gen-cross-files.sh [abi ...]
#
# With no arguments all four ABIs are generated; otherwise only the named ones.
# The per-ABI install prefix (<base>/<abi>) is taken from
# $NORDSTJERNEN_ANDROID_SYSROOT and baked into each cross-file's
# pkg_config_libdir so Meson resolves the already-built dependencies.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

require_ndk

SYSROOT_BASE="${NORDSTJERNEN_ANDROID_SYSROOT:-${ANDROID_DIR}/sysroot}"
mkdir -p "${CROSS_DIR}"

gen_one() {
  local abi="$1"
  set_abi_env "${abi}"
  local prefix="${SYSROOT_BASE}/${abi}"
  local out="${CROSS_DIR}/${abi}.cross"

  cat > "${out}" <<EOF
# Auto-generated by android/scripts/gen-cross-files.sh -- DO NOT EDIT BY HAND.
# Target ABI: ${abi}   NDK API: ${ANDROID_API}
[constants]
ndk_bin = '${NDK_BIN}'

[binaries]
c          = ndk_bin / '${ABI_CLANG_TRIPLE}-clang'
cpp        = ndk_bin / '${ABI_CLANG_TRIPLE}-clang++'
ar         = ndk_bin / 'llvm-ar'
strip      = ndk_bin / 'llvm-strip'
ranlib     = ndk_bin / 'llvm-ranlib'
nm         = ndk_bin / 'llvm-nm'
ld         = ndk_bin / 'ld.lld'
pkg-config = 'pkg-config'

[built-in options]
# NDK clang already defines __ANDROID_API__ from the android${ANDROID_API} target
# triple, so we don't redefine it here (avoids -Wmacro-redefined noise).
c_args         = ['-fPIC', '-DANDROID']
cpp_args       = ['-fPIC', '-DANDROID']
c_link_args    = ['${PAGE_SIZE_LDFLAG}', '${UNDEF_VER_LDFLAG}']
cpp_link_args  = ['${PAGE_SIZE_LDFLAG}', '${UNDEF_VER_LDFLAG}']
default_library = 'shared'

[properties]
# Built dependencies install with an absolute prefix, so their .pc files carry
# absolute paths; we therefore set pkg_config_libdir but NOT sys_root.
pkg_config_libdir = '${prefix}/lib/pkgconfig'
needs_exe_wrapper = true

[host_machine]
system     = 'android'
cpu_family = '${ABI_CPU_FAMILY}'
cpu        = '${ABI_CPU}'
endian     = '${ABI_ENDIAN}'
EOF
  log "wrote ${out}"
}

if [ "$#" -ge 1 ]; then
  ABIS=("$@")
else
  ABIS=("${ALL_ABIS[@]}")
fi

for abi in "${ABIS[@]}"; do
  is_valid_abi "${abi}" || die "unknown ABI: ${abi}"
  gen_one "${abi}"
done
